exclude: |
  (^dist/)|(^build/)|(^node_modules/)|
  (^\.venv/)|(^venv/)|
  (^spoon_audit_report_.*\.html$)

repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
        args: [--check, --diff]
        stages: [commit, push]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
        args:
          
          - --max-line-length=88
          - --extend-ignore=E203,W503
          
          - >-
            --per-file-ignores=
            tests/*.py:F401,E302,W293,W292,E501,
            tests/conftest.py:E302,W293,W292,E501
        stages: [commit, push]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args:
          
          - --ignore-missing-imports
          - --allow-untyped-defs
          - --implicit-optional
          
          - >-
            --exclude=
            ^(tests/|web-dashboard/|extension/|
            analysis/ai_analyzer\.py|cli/config\.py|
            analysis/pipeline_manager\.py|analysis/parser\.py)$
        stages: [commit, push]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        stages: [commit]
      - id: end-of-file-fixer
        stages: [commit]
      - id: trailing-whitespace
        stages: [commit]
      - id: debug-statements
        stages: [commit]
