repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
        args: [--check, --diff]
        stages: [commit, push]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
        args: [--max-line-length=88]
        stages: [commit, push]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        stages: [commit, push]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        stages: [commit]            
      - id: end-of-file-fixer
        stages: [commit]            
      - id: trailing-whitespace
        stages: [commit]            
      - id: debug-statements
        stages: [commit]            
