name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Show Python version
        run: python -V

      - name: Run pre-commit (check-only on push stage)
        run: pre-commit run --all-files --hook-stage push --show-diff-on-failure

      - name: Run tests with coverage
        run: |
          pytest --maxfail=1 --disable-warnings -q \
            --cov=analysis --cov=cli \
            --cov-report=term-missing \
            --cov-report=xml:coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          flags: unittests
          # token: ${{ secrets.CODECOV_TOKEN }}   # uncomment for private repos
