name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]   # <-- quote these

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run black
        run: pre-commit run black --all-files

      - name: Run flake8
        run: pre-commit run flake8 --all-files

      - name: Run mypy
        run: pre-commit run mypy --all-files

      - name: Run tests with coverage
        run: |
          pytest --maxfail=1 --disable-warnings -q \
            --cov=analysis --cov=cli \
            --cov-report=term-missing \
            --cov-report=xml:coverage.xml   # <-- generate the file Codecov expects

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          flags: unittests
